apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-exporter-configmap
data:
  config.yml: |
    discovery:
      exportedTagsOnMetrics:
        ec2:
          - Name
          - type
        ecs:
          - ClusterName
          - ServiceName
      jobs:
      - regions: [eu-west-2]
        type: AWS/EC2
        length: 300
        metrics:
          - name: CPUUtilization
            statistics: [Average]
            nilToZero: true
      - regions: [eu-west-2]
        type: AWS/ECS
        length: 300
        metrics:
          - name: CPUUtilization
            statistics: [Average]
            nilToZero: true
      - regions: [eu-west-2]
        type: AWS/ECS
        length: 300
        metrics:
          - name: MemoryUtilization
            statistics: [Average]
            nilToZero: true


# GP_VMseries,GP_VMseries_dimensions,SOP_VMseries,SOP_VMseries_dimensions
