apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-exporter-configmap
data:
{{ if eq .Values.environment "production"  }}
  config.yml: |
    discovery:
      exportedTagsOnMetrics:
        ec2:
          - Name
          - type
        ecs:
          - ClusterName
          - ServiceName
        s3:
          - BucketName
          - StorageType
      jobs:
      - regions: [eu-west-2]
        roleArns:
          - {{ .Values.cloudwatchExporter.assumeDevelopmentRoleArn }}
          - {{ .Values.cloudwatchExporter.assumePreProductionRoleArn }}
          - {{ .Values.cloudwatchExporter.assumeProductionRoleArn }}
        type: AWS/EC2
        length: 300
        metrics:
          - name: CPUUtilization
            statistics: [Average]
            nilToZero: true
      - regions: [eu-west-2]
        type: AWS/ECS
        length: 300
        metrics:
          - name: CPUUtilization
            statistics: [Average, Minimum, Maximum]
            nilToZero: true
      - regions: [eu-west-2]
        type: AWS/ECS
        length: 300
        metrics:
          - name: MemoryUtilization
            statistics: [Average]
            nilToZero: true
      - regions: [eu-west-2]
        type: AWS/RDS
        length: 300
        metrics:
          - name: FreeStorageSpace
            statistics: [Average]
            nilToZero: true
      - regions: [eu-west-2]
        type: AWS/S3
        length: 300
        metrics:
          - name: BucketSizeBytes
            statistics: [Average]
            nilToZero: true
{{ else }}
# for development and preproduction environments we only export a few metrics from that account
# this is it keep the costs of calling the cloudwatch API lower
  config.yml: |
    discovery:
      exportedTagsOnMetrics:
        ec2:
          - Name
          - type
        ecs:
          - ClusterName
          - ServiceName
        s3:
          - BucketName
          - StorageType
      jobs:
      - regions: [eu-west-2]
        type: AWS/EC2
        length: 300
        metrics:
          - name: CPUUtilization
            statistics: [Average]
            nilToZero: true
      - regions: [eu-west-2]
        type: AWS/ECS
        length: 300
        metrics:
          - name: CPUUtilization
            statistics: [Average, Minimum, Maximum]
            nilToZero: true
      - regions: [eu-west-2]
        type: AWS/ECS
        length: 300
        metrics:
          - name: MemoryUtilization
            statistics: [Average]
            nilToZero: true
      - regions: [eu-west-2]
        type: AWS/RDS
        length: 300
        metrics:
          - name: FreeStorageSpace
            statistics: [Average]
            nilToZero: true
      - regions: [eu-west-2]
        type: AWS/S3
        length: 300
        metrics:
          - name: BucketSizeBytes
            statistics: [Average]
            nilToZero: true
{{ end }}


# GP_VMseries,GP_VMseries_dimensions,SOP_VMseries,SOP_VMseries_dimensions
