apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cloudwatch-exporter
  labels:
    app: cloudwatch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudwatch-exporter
  template:
    metadata:
      labels:
        app: cloudwatch-exporter
    spec:
      containers:
      - name: cloudwatch-exporter
        image: {{ .Values.cloudwatchExporter.image }}
        ports:
        - containerPort: 5000
        args:
          - "--config.file=/config/config.yml"
        volumeMounts:
        - name: configuration
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: configuration
        configMap:
          name: cloudwatch-exporter-configmap
          items:
          - key: "config.yml"
            path: "config.yml"