apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cloudwatch-exporter
spec:
  selector:
    app: cloudwatch-exporter
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000