apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-exporter-configmap
data:
  config.yml: |
    region: eu-west-2
    metrics:
    - aws_namespace: AWS/EC2
      aws_metric_name: CPUUtilization
      aws_statistics: [Average]
      aws_dimensions: [InstanceId]
    - aws_namespace: AWS/ECS
      aws_metric_name: CPUUtilization
      aws_statistics: [Average]
      aws_dimensions: [ClusterName, ServiceName]
    - aws_namespace: AWS/ECS
      aws_metric_name: MemoryUtilization
      aws_statistics: [Average]
      aws_dimensions: [ClusterName, ServiceName]
