environment: ""
prometheus:
  image: ""
thanos:
  image: ""
  compactor:
    enabled: false
cloudwatchExporter:
  image: ""
  assumeDevelopmentRoleArn: ""
  assumePreProductionRoleArn: ""
  assumeProductionRoleArn: ""
  assumeSharedServicesRoleArn: ""
prometheusThanosStorageBucket:
  bucketName: ""
  endpoint: "s3.eu-west-2.amazonaws.com"
  kmsKeyId: ""